In [1]:
import numpy as numpy
import pandas as pd

# Data Familiarization

In [4]:
df = pd.read_csv("Assignment DataSet.csv")
df.head(10)

,Unnamed: 0,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,tolazamide,examide,citoglipton,insulin,glyburide-metformin,glipizide-metformin,metformin-rosiglitazone,change,diabetesMed,readmitted
0,0,41186889,Caucasian,Female,[80-90),1,6,7,13,69,...,No,No,Steady,Steady,No,No,No,No,Yes,NO
1,1,83591073,Caucasian,Female,[80-90),6,1,17,5,34,...,No,No,Steady,No,No,No,No,No,No,NO
2,2,68337009,Other,Male,[60-70),1,2,1,1,37,...,No,No,Steady,Steady,No,No,No,No,Yes,NO
3,3,73175076,Caucasian,Male,[40-50),1,1,7,4,56,...,No,No,Steady,Up,No,No,No,Ch,Yes,YES
4,4,31718349,Caucasian,Female,[70-80),1,1,7,1,38,...,No,No,Steady,No,No,No,No,No,No,NO
5,5,20909367,Hispanic,Female,[80-90),2,6,1,2,61,...,No,No,No,Down,No,No,No,Ch,Yes,NO
6,6,86870088,AfricanAmerican,Female,[50-60),1,1,7,3,26,...,No,No,No,Down,No,No,No,Ch,Yes,YES
7,7,52043301,Caucasian,Male,[60-70),3,1,1,6,66,...,No,No,No,No,No,No,No,No,No,NO
8,8,58716846,AfricanAmerican,Female,[60-70),1,13,7,9,74,...,No,No,No,Steady,No,No,No,No,Yes,NO
9,9,102729258,Caucasian,Male,[40-50),6,1,7,12,68,...,No,No,Steady,Up,No,No,No,Ch,Yes,NO